### ISSUE TITLE
Player cannot move into the top 3 lanes, no mobs spawning here

### ISSUE THREAD

**Issue by meganroxburgh** [UQcsse3200/2023-studio-3#115]
## Description
The player cannot move into the top 3 lanes of the map on the main branch. General mobs are also not moving in these lanes.

## How To Reproduce
Steps to reproduce the behaviour:
1. Run the game
2. Move the player up to the lane, and you will see that they stop when they reach the third lane from the top

## Expected Behaviour
The player should be able to move freely across all 8 lanes and the general mobs should spawn and move in these lanes.

## Screenshots
Player cannot move above this red line.
<img width="696" alt="image" src="https://github.com/UQcsse3200/2023-studio-3/assets/128758122/14399750-65d6-4cf9-b55b-ce4f8c4abc39">

**Comment by Moksh-Mehta7** [comment]
fixed
