### ISSUE TITLE
[Team 1] Creation of Patrick Boss

### ISSUE THREAD

**Issue by gregchan550** [UQcsse3200/2023-studio-3#203]
# **Description**
**Task:** [Create the Patrick Boss](#3).
**Feature:** [All-Mobs Enhancement](#2)

Teleport: teleport to any location on the map
Melee: teleport to closest human entity and deal damage
Range: teleport to random location and shoot random effect projectile
Half health: Shoot 5 random aoe effect projectiles
Animation: animate all different abilities and movements
Sound effects: implement all sounds effects
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Teleport (Sep. 19)
- [x] Melee (Sep. 21)
- [x] Range (Sep. 23)
- [x] Half Health (Sep. 25)
- [x] Animation (Sep. 27)
- [x] Sound effects (Sep. 29)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Boss Features]()
- [Animations]()
 
# **Member**
- Gregory (@gregchan550) (Gregory)

**Comment by The-AhmadAA** [comment]
Patrick boss seems to have an issue with melee attack causing a NullPointerException?
![image](https://github.com/UQcsse3200/2023-studio-3/assets/111224176/1318f8b0-cef9-4cc2-b264-172b415ff227)
This was happening with no towers and no engineers in the game area
