### ISSUE TITLE
Pause button misalignment depending on screen size.

### ISSUE THREAD

**Issue by AlasdairS4698737** [UQcsse3200/2023-studio-3#233]
## Description
The screen positioning for the pause menu background uses the entity coordinates, while the pause menu buttons use padTop/Left/Bottom/Right methods. This results in the pause menu buttons not aligning with the background depending on the screen size.

## How To Reproduce
1. Start a game
2. Open the game's pause menu
3. If the buttons are correctly aligned, re-try steps 1 and 2 with different screen resolution settings.

## Expected Behaviour
The pause menu buttons are expected to stay within the background for all screen sizes.

**Comment by The-AhmadAA** [comment]
Closing this issue as resolved in PR #258
